### PR TITLE
Add compatibility for Symfony 4 and 5

### LINKED ISSUE #27: Symfony 4 and 5 compatibility
Hi,

I cannot used your library with Symfony > 3.4 (4 and 5) because dom-crawler and css-selector are in ~3.0... 
Would it be possible to update these dependencies ?

Thanks !

### PR DESCRIPTION
**Pull request by GCalmels**
Update `symfony/dom-crawler`and `symfony/css-selector` in `composer.json` to fix https://github.com/dusterio/link-preview/issues/27

### CODE REVIEW

**Comment by GCalmels** [comment]
Hey @dusterio, could I have a response to this PR ? You could reject it but I would like to know if I need to find a new package or to fork your repo for a project ?
Thank you !

**Comment by C0kkie** [comment]
@dusterio Could you please merge it? Would be important to run with php 8

**Comment by dusterio** [comment]
@C0kkie sure thing, thanks!

**Comment by C0kkie** [comment]
Thanks

**Pull request merged**
